#
# Makefile for the client example
#

include $(APPDIR)/Make.defs

# Your main entry point
MAINSRC = client.c

# The name of your application
PROGNAME = $(CONFIG_EXAMPLES_CLIENT_PROGNAME)
PRIORITY = $(CONFIG_EXAMPLES_CLIENT_PRIORITY)
STACKSIZE = $(CONFIG_EXAMPLES_CLIENT_STACKSIZE)

# Build the application
MODULE = $(CONFIG_EXAMPLES_CLIENT)

include $(APPDIR)/Application.mk
